name: nlp-19
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.0=py37_0
  - asn1crypto=0.24.0=py37_1003
  - attrs=19.1.0=py_0
  - backcall=0.1.0=py37_0
  - blas=1.0=openblas
  - bokeh=1.3.4=py37_0
  - boto=2.49.0=py_0
  - boto3=1.9.215=py_0
  - botocore=1.12.215=py_0
  - bz2file=0.98=py_0
  - ca-certificates=2019.6.16=hecc5488_0
  - certifi=2019.6.16=py37_1
  - cffi=1.12.3=py37hccf1714_0
  - chardet=3.0.4=py37_1003
  - cryptography=2.7=py37h212c5bf_0
  - cymem=2.0.2=py37h6de7cb9_0
  - cython-blis=0.2.4=py37h01d97ff_1
  - decorator=4.4.0=py37_1
  - docutils=0.15.2=py37_0
  - freetype=2.9.1=hb4e5f40_0
  - funcy=1.13=py_0
  - future=0.17.1=py37_1000
  - gensim=3.4.0=py37h1de35cc_0
  - idna=2.8=py37_1000
  - ipykernel=5.1.2=py37h39e3cac_0
  - ipython=7.7.0=py37h39e3cac_0
  - ipython_genutils=0.2.0=py37_0
  - jedi=0.15.1=py37_0
  - jinja2=2.10.1=py37_0
  - jmespath=0.9.4=py_0
  - joblib=0.13.2=py37_0
  - jpeg=9b=he5867d9_2
  - jsonschema=3.0.2=py37_0
  - jupyter_client=5.3.1=py_0
  - jupyter_core=4.5.0=py_0
  - libblas=3.8.0=12_openblas
  - libcblas=3.8.0=12_openblas
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - libgfortran=4.0.0=2
  - liblapack=3.8.0=12_openblas
  - libopenblas=0.3.7=h4bb4525_1
  - libpng=1.6.37=ha441bb4_0
  - libsodium=1.0.16=h3efe00b_0
  - libtiff=4.0.10=hcb84e12_2
  - llvm-openmp=8.0.1=h770b8ee_0
  - markupsafe=1.1.1=py37h1de35cc_0
  - murmurhash=1.0.0=py37hfc679d8_0
  - ncurses=6.1=h0a44026_1
  - numexpr=2.7.0=py37h86efe34_0
  - numpy=1.17.0=py37h6b0580a_0
  - olefile=0.46=py37_0
  - openssl=1.1.1c=h01d97ff_0
  - packaging=19.1=py37_0
  - pandas=0.25.0=py37h0a44026_0
  - parso=0.5.1=py_0
  - pexpect=4.7.0=py37_0
  - pickleshare=0.7.5=py37_0
  - pillow=6.1.0=py37hb68e598_0
  - pip=19.2.2=py37_0
  - plac=0.9.6=py_1
  - preshed=2.0.1=py37h6de7cb9_0
  - prompt_toolkit=2.0.9=py37_0
  - ptyprocess=0.6.0=py37_0
  - pycparser=2.19=py37_1
  - pygments=2.4.2=py_0
  - pyldavis=2.1.2=py_0
  - pyopenssl=19.0.0=py37_0
  - pyparsing=2.4.2=py_0
  - pyrsistent=0.15.4=py37h01d97ff_0
  - pysocks=1.7.0=py37_0
  - python=3.7.4=h359304d_1
  - python-dateutil=2.8.0=py37_0
  - pytz=2019.2=py_0
  - pyyaml=5.1.2=py37h1de35cc_0
  - pyzmq=18.1.0=py37h0a44026_0
  - readline=7.0=h1de35cc_5
  - requests=2.22.0=py37_1
  - s3transfer=0.2.1=py37_0
  - scikit-learn=0.21.2=py37hebd9d1a_0
  - scipy=1.3.1=py37h7e0e109_2
  - setuptools=41.0.1=py37_0
  - six=1.12.0=py37_0
  - smart_open=1.8.4=py_0
  - spacy=2.1.8=py37h770b8ee_0
  - sqlite=3.29.0=ha441bb4_0
  - srsly=0.1.0=py37h6de7cb9_0
  - thinc=7.0.8=py37h770b8ee_0
  - tk=8.6.8=ha441bb4_0
  - tornado=6.0.3=py37h1de35cc_0
  - tqdm=4.34.0=py_0
  - traitlets=4.3.2=py37_0
  - urllib3=1.25.3=py37_0
  - wasabi=0.2.2=py_0
  - wcwidth=0.1.7=py37_0
  - wheel=0.33.4=py37_0
  - xz=5.2.4=h1de35cc_4
  - yaml=0.1.7=hc338f04_2
  - zeromq=4.3.1=h0a44026_3
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.3.7=h5bba6e5_0
  - pip:
    - pytorch-transformers==1.0.0
    - spacy-pytorch-transformers==0.2.0
    - https://github.com/explosion/spacy-models/releases/download/en_core_web_md-2.1.0/en_core_web_md-2.1.0.tar.gz
    - https://github.com/explosion/spacy-models/releases/download/en_pytt_bertbaseuncased_lg-2.1.1/en_pytt_bertbaseuncased_lg-2.1.1.tar.gz
    - ftfy==5.6
    - regex==2019.8.19
    - sentencepiece==0.1.83
    - torch==1.2.0
    - torchcontrib==0.0.2
prefix: /anaconda3/envs/nlp-19

